spring:
  config.import:
    - classpath:application-service.yml
  application:
    name: starter-api
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8090